set CLAUDE_CODE_FEATURE_PROACTIVE=1
set CLAUDE_CODE_FEATURE_KAIROS=1

rm -f .bun-build* 
rm -rf node_modules/.cache
set CLAUDE_CODE_VERBOSE=1
set CLAUDE_CODE_USE_NATIVE_FILE_SEARCH=1
set CLAUDE_CODE_GLOB_TIMEOUT_SECONDS=15
set DEBUG0=0
set CLAUDE_CODE_CONSOLE_DEBUG=1
set EMBEDDED_SEARCH_TOOLS=0
set STREAM_FLUSH_MS=5
set CLAUDE_CODE_ATTRIBUTION_HEADER=0
set CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
set CLAUDE_CODE_ENABLE_TELEMETRY=0
set CLAUDE_ENABLE_STREAM_WATCHDOG=0
set BASH_DEFAULT_TIMEOUT_MS=600000
set STREAM_IDLE_TIMEOUT_MS=600000
set API_TIMEOUT_MS=600000
set CLAUDE_STREAM_IDLE_TIMEOUT_MS=1080000
set BASH_MAX_TIMEOUT_MS=600000
set MCP_TIMEOUT=100
set CLAUDE_CODE_SIMPLE=0
set MSYS_NO_PATHCONV=1
set USE_BUILTIN_RIPGREP=1
set CLAUDE_CODE_DISABLE_CIC=1
set CLAUDE_CODE_ATTRIBUTION_HEADER=0
set CLAUDE_CODE_MAX_CONTEXT_TOKENS=250000
set CLAUDE_CODE_MAX_OUTPUT_TOKENS=40000
set CLAUDE_CODE_AUTO_COMPACT_WINDOW=250000
set CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=90
set USER_TYPE=ant0
set ENABLE_LSP_TOOL=1
set NODE_ENV=development
set OLLAMA_GPU_OVERHEAD=0
set CLAUDE_CODE_SHELL_WANT_BASH=1
set CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1
set OLLAMA_FLASH_ATTENTION=1
set OLLAMA_KV_CACHE_TYPE=f16

set CLAUDE_CODE_FEATURE_PROACTIVE=1
set CLAUDE_CODE_FEATURE_KAIROS=1
set CLAUDE_CODE_FEATURE_KAIROS_BRIEF=1
set CLAUDE_CODE_FEATURE_KAIROS_CHANNELS=1
set CLAUDE_CODE_FEATURE_BRIDGE_MODE=1
set CLAUDE_CODE_FEATURE_DAEMON=1
set CLAUDE_CODE_FEATURE_VOICE_MODE=1
set CLAUDE_CODE_FEATURE_HISTORY_SNIP=1
set CLAUDE_CODE_FEATURE_CCR_REMOTE_SETUP=1
set CLAUDE_CODE_FEATURE_EXPERIMENTAL_SKILL_SEARCH=1
set CLAUDE_CODE_FEATURE_KAIROS_GITHUB_WEBHOOKS=1
set CLAUDE_CODE_FEATURE_ULTRAPLAN=1
set CLAUDE_CODE_FEATURE_TORCH=1
set CLAUDE_CODE_FEATURE_UDS_INBOX=1
set CLAUDE_CODE_FEATURE_FORK_SUBAGENT=1
set CLAUDE_CODE_FEATURE_WORKFLOW_SCRIPTS=1
set CLAUDE_CODE_FEATURE_MCP_SKILLS=1
set CLAUDE_CODE_FEATURE_AGENT_TRIGGERS=1
set CLAUDE_CODE_FEATURE_CCR_AUTO_CONNECT=1
set CLAUDE_CODE_FEATURE_CCR_MIRROR=1
set CLAUDE_CODE_FEATURE_CACHED_MICROCOMPACT=1
set CLAUDE_CODE_FEATURE_CONNECTOR_TEXT=1
set CLAUDE_CODE_FEATURE_TRANSCRIPT_CLASSIFIER=1
set CLAUDE_CODE_FEATURE_BASH_CLASSIFIER=1
set CLAUDE_CODE_FEATURE_COORDINATOR_MODE=1
set CLAUDE_CODE_FEATURE_EXTRACT_MEMORIES=1
set CLAUDE_CODE_FEATURE_DOWNLOAD_USER_SETTINGS=1
set CLAUDE_CODE_FEATURE_COMMIT_ATTRIBUTION=1
set CLAUDE_CODE_FEATURE_STREAMLINED_OUTPUT=1
set CLAUDE_CODE_FEATURE_NATIVE_CLIENT_ATTESTATION=1
set CLAUDE_CODE_FEATURE_TOKEN_BUDGET=1
set CLAUDE_CODE_FEATURE_TEMPLATES=1
set CLAUDE_CODE_FEATURE_CHICAGO_MCP=1
set CLAUDE_CODE_FEATURE_BG_SESSIONS=1
set CLAUDE_CODE_FEATURE_BYOC_ENVIRONMENT_RUNNER=1
set CLAUDE_CODE_FEATURE_SELF_HOSTED_RUNNER=1
set CLAUDE_CODE_FEATURE_REACTIVE_COMPACT=1
set CLAUDE_CODE_FEATURE_CONTEXT_COLLAPSE=1
set CLAUDE_CODE_FEATURE_PROMPT_CACHE_BREAK_DETECTION=1
set CLAUDE_CODE_FEATURE_VERIFICATION_AGENT=1
set CLAUDE_CODE_FEATURE_AGENT_MEMORY_SNAPSHOT=1
set CLAUDE_CODE_FEATURE_BREAK_CACHE_COMMAND=1
set CLAUDE_CODE_FEATURE_NEW_INIT=1
set CLAUDE_CODE_FEATURE_MEMORY_SHAPE_TELEMETRY=1
set CLAUDE_CODE_FEATURE_TEAMMEM=1
set CLAUDE_CODE_FEATURE_DIRECT_CONNECT=1
set CLAUDE_CODE_FEATURE_LODESTONE=1
set CLAUDE_CODE_FEATURE_SSH_REMOTE=1
set CLAUDE_CODE_FEATURE_UPLOAD_USER_SETTINGS=1
set CLAUDE_CODE_FEATURE_HARD_FAIL=1

set CLAUDE_CODE_FEATURE_ABLATION_BASELINE=1

REM === 高级性能/分析功能 ===
set CLAUDE_CODE_FEATURE_SHOT_STATS=0
set CLAUDE_CODE_PROFILE_QUERY=0
set CLAUDE_CODE_PROFILE_STARTUP=0
set CLAUDE_CODE_FEATURE_ENHANCED_TELEMETRY_BETA=0
set CLAUDE_CODE_PERFETTO_TRACE=0
set CLAUDE_CODE_FEATURE_PERFETTO_TRACING=0
set CLAUDE_CODE_PERFETTO_WRITE_INTERVAL_S=30
set CLAUDE_CODE_DEBUG_LOG_LEVEL=error
set CLAUDE_CODE_FEATURE_UNATTENDED_RETRY=0
set CLAUDE_CODE_RETRY_WATCHDOG=0
set CLAUDE_CODE_MAX_RETRIES=3
set CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS=5000
set CLAUDE_CODE_API_KEY_HELPER_TTL_MS=300000

REM === 增强 Agent/团队功能 ===
set CLAUDE_CODE_FEATURE_ULTRATHINK=1
set CLAUDE_CODE_FEATURE_MONITOR_TOOL=1
set CLAUDE_CODE_FEATURE_REVIEW_ARTIFACT=1
set CLAUDE_CODE_FEATURE_SKILL_IMPROVEMENT=1
set CLAUDE_CODE_FEATURE_AGENT_TRIGGERS_REMOTE=1
set CLAUDE_CODE_FEATURE_KAIROS_PUSH_NOTIFICATION=1
set CLAUDE_CODE_FEATURE_COWORKER_TYPE_TELEMETRY=1
set CLAUDE_CODE_FEATURE_BUILDING_CLAUDE_APPS=1
set CLAUDE_CODE_FEATURE_RUN_SKILL_GENERATOR=1
set CLAUDE_CODE_MAX_CONCURRENT_SUBAGENTS=8
set CLAUDE_CODE_MAX_SUBAGENT_SPAWN_DEPTH=4
set CLAUDE_CODE_MAX_WEB_SEARCHES_PER_SESSION=15

REM === UI/UX 增强 ===
set CLAUDE_CODE_FEATURE_AUTO_THEME=1
set CLAUDE_CODE_FEATURE_HISTORY_PICKER=1
set CLAUDE_CODE_FEATURE_MCP_RICH_OUTPUT=1
set CLAUDE_CODE_FEATURE_HOOK_PROMPTS=1
set CLAUDE_CODE_FEATURE_COMPACTION_REMINDERS=1
set CLAUDE_CODE_FEATURE_SKIP_DETECTION_WHEN_AUTOUPDATES_DISABLED=1
set CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN=1
set CLAUDE_CODE_NO_FLICKER=0
set CLAUDE_CODE_DISABLE_MOUSE_CLICKS=1
set CLAUDE_CODE_SYNTAX_HIGHLIGHT=1
set CLAUDE_CODE_FORCE_SYNC_OUTPUT=1
set CLAUDE_CODE_DISABLE_TERMINAL_TITLE=0
set CLAUDE_CODE_SESSIONEND_HOOKS_TIMEOUT_MS=5000

REM === 沙箱/安全增强 ===
set CLAUDE_CODE_DISABLE_CLAUDE_MDS=1
set CLAUDE_CODE_DUMP_AUTO_MODE=1
set CLAUDE_CODE_DISABLE_COMMAND_INJECTION_CHECK=0
set CLAUDE_CODE_PROXY_RESOLVES_HOSTS=0
set CLAUDE_CODE_DISABLE_CRON=0
set CLAUDE_CODE_UNDERCOVER=0
set CLAUDE_CODE_BUBBLEWRAP=0

REM === 远程桥接/桌面功能 ===
set CLAUDE_CODE_REMOTE=1
set CLAUDE_CODE_LOCAL_BRIDGE=1
set CLAUDE_CODE_LOCAL_BRIDGE_URL=http://localhost:5678

REM === 文件/路径功能 ===
set CLAUDE_CODE_FILE_READ_MAX_OUTPUT_TOKENS=8000
set CLAUDE_CODE_WORKFLOW_SIZE=40
set CLAUDE_CODE_MCP_AUTO_BACKGROUND_MS=30000
set CLAUDE_CODE_OTEL_CONTENT_MAX_LENGTH=10000
set CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS=500
set CLAUDE_CODE_PLUGIN_USE_ZIP_CACHE=1
set CLAUDE_CODE_PLUGIN_GIT_TIMEOUT_MS=180000
set CLAUDE_CODE_DISABLE_PRECOMPACT_SKIP=0
set CLAUDE_CODE_SAVE_HOOK_ADDITIONAL_CONTEXT=1

REM === 调试/诊断 ===
set CLAUDE_CODE_DEBUG_REPAINTS=0
set CLAUDE_CODE_COMMIT_LOG=0
set CLAUDE_CODE_STREAM_CLOSE_TIMEOUT=60
set CLAUDE_CODE_DIAGNOSTICS_FILE=debug_diagnostics.log
set CLAUDE_CODE_STALL_TIMEOUT_MS_FOR_TESTING=60000
set CLAUDE_CODE_PWSH_PARSE_TIMEOUT_MS=10000
set CLAUDE_CODE_SLOW_OPERATION_THRESHOLD_MS=1000

REM === API/模型增强 ===
set CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK=0
set CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING=0
set CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=0

REM === 新增 feature() 标志 (编译�? �?这些�?d.bat 原版中缺�?===
set CLAUDE_CODE_FEATURE_MCP_UI=1
set CLAUDE_CODE_FEATURE_AWAY_SUMMARY=1
set CLAUDE_CODE_FEATURE_OVERFLOW_TEST_TOOL=1
set CLAUDE_CODE_FEATURE_SLOW_OPERATION_LOGGING=1
set CLAUDE_CODE_FEATURE_POWERSHELL_AUTO_MODE=1
set CLAUDE_CODE_FEATURE_NATIVE_CLIPBOARD_IMAGE=1
set CLAUDE_CODE_FEATURE_BUILTIN_EXPLORE_PLAN_AGENTS=1
set CLAUDE_CODE_FEATURE_TREE_SITTER_BASH=1
set CLAUDE_CODE_FEATURE_TREE_SITTER_BASH_SHADOW=1
set CLAUDE_CODE_FEATURE_ALLOW_TEST_VERSIONS=0
set CLAUDE_CODE_FEATURE_KAIROS_DREAM=1

REM === 新增运行�?env var ===
set CLAUDE_CODE_EAGER_FLUSH=1
set CLAUDE_CODE_DISABLE_FAST_MODE=0
set CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION=1
REM set CLAUDE_CODE_ENABLE_CFC=1
set CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING=1
set CLAUDE_CODE_RESUME_INTERRUPTED_TURN=1
set CLAUDE_CODE_EMIT_TOOL_USE_SUMMARIES=1
set CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES=0
set CLAUDE_CODE_WORKSPACE_HOST_PATHS=.
set CLAUDE_CODE_IDE_HOST_OVERRIDE=localhost
set CLAUDE_CODE_IDE_SKIP_VALID_CHECK=0
set CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS=0
set CLAUDE_CODE_REPL=1
set CLAUDE_CODE_IS_COWORK=0
set CLAUDE_CODE_ADDITIONAL_PROTECTION=0
set CLAUDE_CODE_EXIT_AFTER_STOP_DELAY=30000
set CLAUDE_CODE_PLAN_V2_AGENT_COUNT=3
set CLAUDE_CODE_MCP_INSTR_DELTA=0
set CLAUDE_CODE_DISABLE_METRICS=0
set CLAUDE_CODE_FORCE_FLUX_NATIVE=0
set CLAUDE_CODE_CONSOLE_DEBUG=1

REM === Claude Code 内部 env var (�?CLAUDE_CODE_) ===
set CLAUDE_CODE_DEV_VERSION=local
set CLAUDE_CODE_DEV_BUILD_TIME=local
set CLAUDE_CODE_EMIT_SESSION_STATE_EVENTS=1
set CLAUDE_CODE_USE_COWORK_PLUGINS=0
set CLAUDE_CODE_DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL=0
set CLAUDE_CODE_SUBPROCESS_ENV_SCRUB=0
set CLAUDE_CODE_QUESTION_PREVIEW_FORMAT=brief
set CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST=0

REM Disable all simple-mode restrictions
set CLAUDE_CODE_SIMPLE=0
set CLAUDE_CODE_DISABLE_THINKING=0
set DISABLE_INTERLEAVED_THINKING=0
set DISABLE_COMPACT=0
set DISABLE_AUTO_COMPACT=0
set CLAUDE_CODE_DISABLE_AUTO_MEMORY=0
set DISABLE_BACKGROUND_TASKS=0

set CLAUDE_CODE_FEATURE_DUMP_SYSTEM_PROMPT=1
set CLAUDE_CODE_FEATURE_WEB_BROWSER_TOOL=1







# bun pm cache rm
# rm -rf node_modules dist build .next out
rm -rf .react_compiler_cache
rm -rf node_modules/.cache/react-compiler
rm -rf dist
rm -rf build
rm -rf .doge/build       
rm -rf out                  
rm -f tsconfig.tsbuildinfo
rm -f bun.lockb
cd /d D:\doge-code 
del /q src\commands\clear\caches.js src\commands\clear\clear.js src\commands\clear\conversation.js src\commands\clear\index.js src\commands\logout\logout.js src\ink\components\patch_app.js src\generated\status-line-embedded.js 2>nul
rm  -rf .react_compiler_cache
rm  -rf  node_modules\.cache 
rm  -rf  .doge\build 
rm  -rf  dist
rm  -rf  out 
rm  -rf  build
del /q tsconfig.tsbuildinfo
	
# npm cache clean --force
# yarn cache clean

#  rm -rf node_modules
rm -f package-lock.json yarn.lock

#    npm install  #  yarn

# npm run build -- --force   


bun build --define PROACTIVE=true  --define KAIROS=true  --define KAIROS_BRIEF=true   --define KAIROS_CHANNELS=true   --define BRIDGE_MODE=true   --define DAEMON=true   --define VOICE_MODE=true   --define HISTORY_SNIP=true   --define CCR_REMOTE_SETUP=true   --define EXPERIMENTAL_SKILL_SEARCH=true   --define KAIROS_GITHUB_WEBHOOKS=true   --define ULTRAPLAN=true   --define TORCH=true   --define UDS_INBOX=true  --define FORK_SUBAGENT=true  --define WORKFLOW_SCRIPTS=true   --define MCP_SKILLS=true   --define AGENT_TRIGGERS=true   --define CCR_AUTO_CONNECT=true   --define CCR_MIRROR=true   --define CACHED_MICROCOMPACT=true   --define CONNECTOR_TEXT=true   --define TRANSCRIPT_CLASSIFIER=true   --define BASH_CLASSIFIER=true   --define COORDINATOR_MODE=true   --define EXTRACT_MEMORIES=true   --define DOWNLOAD_USER_SETTINGS=true   --define COMMIT_ATTRIBUTION=true   --define STREAMLINED_OUTPUT=true   --define NATIVE_CLIENT_ATTESTATION=true   --define TOKEN_BUDGET=true   --define TEMPLATES=true   --define CHICAGO_MCP=true   --define BG_SESSIONS=true   --define BYOC_ENVIRONMENT_RUNNER=true   --define SELF_HOSTED_RUNNER=true   --define REACTIVE_COMPACT=true   --define CONTEXT_COLLAPSE=true   --define PROMPT_CACHE_BREAK_DETECTION=true   --define VERIFICATION_AGENT=true   --define AGENT_MEMORY_SNAPSHOT=true   --define BREAK_CACHE_COMMAND=true   --define NEW_INIT=true   --define MEMORY_SHAPE_TELEMETRY=true   --define TEAMMEM=true   --define DIRECT_CONNECT=true   --define LODESTONE=true   --define SSH_REMOTE=true   --define UPLOAD_USER_SETTINGS=true   --define HARD_FAIL=true   --define ABLATION_BASELINE=true   --define DUMP_SYSTEM_PROMPT=true   --define WEB_BROWSER_TOOL=true   --define QUICK_SEARCH=true   --define TERMINAL_PANEL=true   --define MESSAGE_ACTIONS=true   --define FILE_PERSISTENCE=true   ./src/entrypoints/cli.tsx   --compile   --outfile ./doge   --external playwright   --external playwright-core
 
REM === Clean up build artifacts from src/ to prevent .js shadowing .ts ===
PowerShell -Command "Get-ChildItem -Path 'src/commands/clear' -Filter '*.js' -ErrorAction SilentlyContinue | Remove-Item -Force"
PowerShell -Command "Get-ChildItem -Path 'src/commands/logout' -Filter '*.js' -ErrorAction SilentlyContinue | Remove-Item -Force"
PowerShell -Command "Get-ChildItem -Path 'src/generated' -Filter '*.js' -ErrorAction SilentlyContinue | Remove-Item -Force"
PowerShell -Command "Get-ChildItem -Path 'src/tools/REPLTool' -Filter '*.js' -ErrorAction SilentlyContinue | Remove-Item -Force"
PowerShell -Command "Get-ChildItem -Path 'src/tools/VerifyPlanExecutionTool' -Filter '*.js' -ErrorAction SilentlyContinue | Remove-Item -Force"
PowerShell -Command "Get-ChildItem -Path 'src' -Recurse -Filter '*.js.map' -ErrorAction SilentlyContinue | Remove-Item -Force"
PowerShell -Command "Remove-Item -Path 'src/globals.d.ts','src/generated/globals.d.ts','src/ink/global.d.ts','src/types/js-cookie.d.ts','src/types/react19.d.ts','src/__tests__/vitest.d.ts' -ErrorAction SilentlyContinue"
echo [*] Build artifacts cleaned from src/

pause
