del debug.log
del debug.txt

# 清除所有旧的 Claude 环境变量
# set ANTHROPIC_API_KEY=#set ANTHROPIC_AUTH_TOKEN=#set CLAUDE_CODE_API_KEY=#set ANTHROPIC_BASE_URL=
set CLAUDE_CODE_VERBOSE=1
set CLAUDE_CODE_USE_NATIVE_FILE_SEARCH=1
set CLAUDE_CODE_GLOB_TIMEOUT_SECONDS=15
set DEBUG0=0
set EMBEDDED_SEARCH_TOOLS=0
# 设置新的#set ANTHROPIC_BASE_URL=http://127.0.0.1:9000#set ANTHROPIC_API_KEY=dummy#set OPENAI_BASE_URL=http://127.0.0.1:8081/v1#set OPENAI_API_KEY=dummy#set ANTHROPIC_BASE_URL=http://127.0.0.1:8081/v1#set ANTHROPIC_API_KEY=dummy#claude#set ANTHROPIC_BASE_URL=http://127.0.0.1:9000/v1
set STREAM_FLUSH_MS=5
set CLAUDE_CODE_ATTRIBUTION_HEADER=0
set CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
set CLAUDE_CODE_ENABLE_TELEMETRY=0
set CLAUDE_ENABLE_STREAM_WATCHDOG=0
set BASH_DEFAULT_TIMEOUT_MS=600000
set STREAM_IDLE_TIMEOUT_MS=600000
set API_TIMEOUT_MS=600000
set CLAUDE_STREAM_IDLE_TIMEOUT_MS=1080000
set BASH_MAX_TIMEOUT_MS=600000
set MCP_TIMEOUT=100
set CLAUDE_CODE_SIMPLE=0
set MSYS_NO_PATHCONV=1
set USE_BUILTIN_RIPGREP=1
set FEATURE_PROACTIVE=1
set FEATURE_KAIROS=1

set CLAUDE_CODE_DISABLE_CIC=1
set CLAUDE_CODE_ATTRIBUTION_HEADER=0
set CLAUDE_CODE_MAX_CONTEXT_TOKENS=128000
set CLAUDE_CODE_MAX_OUTPUT_TOKENS =40000
set CLAUDE_CODE_AUTO_COMPACT_WINDOW=128000
set CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=90
set USER_TYPE=ant0
set ENABLE_LSP_TOOL=1
set NODE_ENV=development
set OLLAMA_GPU_OVERHEAD=0
REM # Shell 配置：默认使用 Windows 原生 cmd.exe 避免 MSYS2 多行参数转义问题
REM # 改为 set CLAUDE_CODE_SHELL=C:/Program Files/Git/bin/bash.exe 可切回 MSYS2 bash
REM set CLAUDE_CODE_SHELL=C:\Windows\System32\cmd.exe
REM set SHELL=C:\Windows\System32\cmd.exe
REM set CLAUDE_CODE_SHELL=powershell  # 使用 PowerShell
REM 
set CLAUDE_CODE_SHELL_WANT_BASH=1  # 即使知道有坑，也要用 bash

set CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1
set OLLAMA_FLASH_ATTENTION=1
set OLLAMA_KV_CACHE_TYPE=f16
if "%1"=="" (
    set DOGE_API_JSON =.doge/api.json
) else (
    set DOGE_API_JSON=.doge/%1.json
)
bun run "D:\doge-code\src\bootstrap-entry.ts"  --debug-file ./debug.txt --dangerously-skip-permissions --verbose --add-dir .   %2 %3
