import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { execSync } from 'child_process';

// 1. 编译 status-line.ts 为 status-line.js
execSync('bun build src/utils/status-line.ts --outfile temp/status-line.js --target=node --format=cjs', { stdio: 'inherit' });

// 2. 读取编译后的 JS 代码
const sourceCode = readFileSync('temp/status-line.js', 'utf-8');

// 3. 转义反引号和 ${}
const escaped = sourceCode.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

// 4. 生成嵌入模块
const output = `// Auto-generated by scripts/embed-status-line.ts
export const STATUS_LINE_SOURCE = \`${escaped}\`;
`;

mkdirSync('src/generated', { recursive: true });
writeFileSync('src/generated/status-line-embedded.ts', output);
writeFileSync('src/generated/status-line-embedded.js', output);
console.log('✅ status-line.ts embedded into src/generated/status-line-embedded.ts');