import { existsSync, readdirSync, writeFileSync } from 'fs'
import { join, dirname, relative } from 'path'

const COMMANDS_DIR = join(import.meta.dir, '..', 'src', 'commands')
const OUTPUT_DIR = join(import.meta.dir, '..', 'src', 'generated')
const OUTPUT_FILE = join(OUTPUT_DIR, 'command-modules.ts')

interface Entry {
  name: string
  relFromGenerated: string
}

function scanCommands(dir: string): Entry[] {
  const entries: Entry[] = []
  const dirNames = new Set<string>()
  const items = readdirSync(dir, { withFileTypes: true })

  // 第一遍：收集目录型命令
  for (const item of items) {
    if (item.isDirectory()) {
      const dirPath = join(dir, item.name)
      const indexPath = join(dirPath, 'index.ts')
      const indexTsxPath = join(dirPath, 'index.tsx')
      let target: string | null = null
      if (existsSync(indexPath)) target = indexPath
      else if (existsSync(indexTsxPath)) target = indexTsxPath
      else continue
      const relPath = relative(OUTPUT_DIR, target).replace(/\\/g, '/')
      entries.push({ name: item.name, relFromGenerated: relPath })
      dirNames.add(item.name)
    }
  }

  // 第二遍：收集单文件命令（跳过与目录同名的，避免冲突）
  for (const item of items) {
    if (item.isFile() && item.name.endsWith('.ts') && !item.name.endsWith('.test.ts')) {
      const commandName = item.name.replace(/\.ts$/, '')
      if (dirNames.has(commandName)) continue // 目录优先
      const filePath = join(dir, item.name)
      const relPath = relative(OUTPUT_DIR, filePath).replace(/\\/g, '/')
      entries.push({ name: commandName, relFromGenerated: relPath })
    }
  }

  return entries.sort((a, b) => a.name.localeCompare(b.name))
}

const commands = scanCommands(COMMANDS_DIR)

const lines: string[] = [
  '// Auto-generated by scripts/gen-command-registry.ts',
  '// DO NOT EDIT — run scripts/gen-command-registry.ts to regenerate',
  '',
  '// Static imports so bun build --compile bundles every command module into the binary.',
  '// COMMAND_MODULES is the runtime registry keyed by command name.',
  '',
]

for (const cmd of commands) {
  const safeName = cmd.name.replace(/-/g, '_')
  lines.push(`import * as mod_${safeName} from '${cmd.relFromGenerated}'`)
}

lines.push('')
lines.push('export const COMMAND_MODULES: Record<string, { default?: any }> = {')
for (const cmd of commands) {
  const safeName = cmd.name.replace(/-/g, '_')
  lines.push(`  '${cmd.name}': mod_${safeName},`)
}
lines.push('}')
lines.push('')
lines.push(`export const COMMAND_COUNT = ${commands.length}`)

writeFileSync(OUTPUT_FILE, lines.join('\n') + '\n', 'utf-8')
console.log(`✅ Generated ${commands.length} command modules → ${OUTPUT_FILE}`)
