import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(__dirname, '..', 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));

const version = pkg.version || '0.0.0';
const buildTime = new Date().toISOString();
const packageUrl = pkg.name || '';
const nativePackageUrl = pkg.name || '';
const versionChangelog = '';
const issuesExplainer = 'https://github.com/kaixings1/doge-code/issues';
const feedbackChannel = '';

const output = `// Auto-generated by scripts/inject-macro.ts
// DO NOT EDIT - Generated at build time

globalThis.MACRO = {
  VERSION: ${JSON.stringify(version)},
  BUILD_TIME: ${JSON.stringify(buildTime)},
  PACKAGE_URL: ${JSON.stringify(packageUrl)},
  NATIVE_PACKAGE_URL: ${JSON.stringify(nativePackageUrl)},
  VERSION_CHANGELOG: ${JSON.stringify(versionChangelog)},
  ISSUES_EXPLAINER: ${JSON.stringify(issuesExplainer)},
  FEEDBACK_CHANNEL: ${JSON.stringify(feedbackChannel)},
};
`;

const outDir = join(__dirname, '..', 'src', 'generated');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'macro.ts'), output);
console.log(`✅ Macro injected: VERSION=${version}`);
