/**
 * Loop Strategy Manuals
 *
 * 超级说明书级别的策略帮助文档
 * 类似于顶级 CLI 工具的 --help 输出
 */

export interface StrategyManual {
  name: string
  displayName: string
  tagline: string
  overview: string
  useCases: string[]
  notSuitableFor: string[]
  coreConcepts: Array<{ term: string; definition: string }>
  architecture: string
  executionFlow: string[]
  parameters: Array<{ name: string; type: string; default: string; description: string }>
  examples: Array<{
    title: string
    complexity: '入门' | '进阶' | '高级' | '专家'
    scenario: string
    command: string
    flow: string[]
    output: string
    tips: string[]
  }>
  bestPractices: string[]
  commonPitfalls: string[]
  comparison: Array<{ strategy: string; whenToUse: string; whenNotToUse: string }>
  performance: string[]
  customization: string[]
}

export const strategyManuals: Record<string, StrategyManual> = {
  langgraph: {
    name: 'langgraph',
    displayName: 'LangGraph 状态机图引擎',
    tagline: '用节点、边和条件跳转构建精确控制流程',
    overview: `LangGraph 是一个基于状态机的图执行引擎，它将任务分解为节点（处理函数）和边（状态转换规则），通过条件跳转实现复杂的流程控制。

与其他策略不同，LangGraph 不依赖 AI 自主决策流程，而是通过预定义的图结构来精确控制执行路径。这使得它特别适合需要确定性流程、可预测执行顺序、以及需要条件分支的场景。

核心能力：
- 有向图执行：节点按图拓扑顺序执行，支持串行和并行
- 条件跳转：根据状态值动态选择下一个节点
- 状态共享：所有节点共享同一个状态对象，通过 reducer 合并更新
- 循环支持：边可以指向之前的节点，实现循环迭代
- 编译优化：图在编译时进行验证和优化`,
    useCases: [
      '需要精确控制执行顺序的工作流',
      '需要条件分支（if/else）的决策流程',
      '需要循环重试直到满足条件的场景',
      '需要状态持久化和恢复的长流程',
      '需要可视化调试执行流程的场景',
      '多阶段审批流程（提交→审核→批准/拒绝）',
    ],
    notSuitableFor: [
      '目标模糊、需要 AI 自主探索的场景',
      '单步骤的简单任务',
      '需要大量创造性思维的任务',
      '对执行顺序没有要求的批处理',
    ],
    coreConcepts: [
      { term: 'StateGraph', definition: '有向图容器，管理所有节点和边' },
      { term: 'Node（节点）', definition: '处理函数 (state) => state，接收当前状态，返回更新后的状态' },
      { term: 'Edge（边）', definition: '无条件转换，从一个节点直接跳转到另一个节点' },
      { term: 'Conditional Edge（条件边）', definition: '条件转换函数 (state) => string，根据状态返回目标节点名称' },
      { term: 'START', definition: '图执行的起始标记，从这里开始执行' },
      { term: 'END', definition: '图执行的终止标记，到达这里执行结束' },
      { term: 'State（状态）', definition: '在节点间传递的共享数据对象' },
      { term: 'Compile（编译）', definition: '将图定义编译为可执行对象，验证图结构合法性' },
    ],
    architecture: [
      '+-----------------------------------------------------------+',
      '|                    LangGraph 架构图                        |',
      '+-----------------------------------------------------------+',
      '|                                                           |',
      '|  +---------+     +---------+     +---------+             |',
      '|  |  START  |---->| analyze |---->|  plan   |             |',
      '|  +---------+     +---------+     +----+----+             |',
      '|                                        |                  |',
      '|                                        V                  |',
      '|  +---------+     +---------+     +---------+             |',
      '|  |  END    |<----| verify  |<----| execute |             |',
      '|  +---------+     +----+----+     +---------+             |',
      '|       ^               |                                  |',
      '|       |               | (条件跳转)                        |',
      '|       |               V                                  |',
      '|       |          +---------+                            |',
      '|       +----------|  plan   | (重试时返回 plan)           |',
      '|                  +---------+                            |',
      '|                                                           |',
      '|  条件跳转规则：                                           |',
      '|  - verify 成功 + 目标达成 → END                          |',
      '|  - verify 成功 + 目标未达成 → plan（继续下一轮）          |',
      '|  - verify 失败 + 重试 < 3  → plan（重新计划）             |',
      '|  - verify 失败 + 重试 >= 3 → END（放弃）                  |',
      '+-----------------------------------------------------------+',
    ].join('\n'),
    executionFlow: [
      '1. 初始化：创建状态对象，设置 step=0, status="start"',
      '2. 进入 START 标记，无条件跳转到 analyze 节点',
      '3. analyze：分析目标，更新状态为 status="analyzed"',
      '4. 跳转到 plan 节点，制定执行计划',
      '5. plan：分解任务，更新状态为 status="planned"',
      '6. 跳转到 execute 节点，执行当前子任务',
      '7. execute：执行子任务，更新任务状态为 "running"',
      '8. 跳转到 verify 节点，验证执行结果',
      '9. verify：检查成功标准，决定下一步',
      '10a. 如果所有任务完成 → 跳转到 END',
      '10b. 如果还有任务未完成 → 跳转到 plan 继续下一轮',
      '10c. 如果重试次数用尽 → 跳转到 END（放弃）',
    ],
    parameters: [
      { name: '--strategy', type: 'string', default: 'langgraph', description: '固定为 langgraph，指定使用状态机图引擎' },
      { name: '--criteria', type: 'string[]', default: '[]', description: '成功标准列表，每个 --criteria 添加一条标准' },
      { name: '--max-iterations', type: 'number', default: '20', description: '最大循环迭代次数，防止无限循环' },
      { name: '--task-budget', type: 'number', default: '∞', description: 'API 调用预算（tokens），超出后自动停止' },
    ],
    examples: [
      {
        title: '入门：创建 Hello World Web 服务器',
        complexity: '入门',
        scenario: '创建一个最简 HTTP 服务器，监听 3000 端口，返回 "Hello World"',
        command: '/loop-langgraph "创建 Node.js Hello World HTTP 服务器，监听 3000 端口"',
        flow: [
          'analyze → 分析需求：需要一个 HTTP 服务器，端口 3000',
          'plan → 生成计划：创建 server.js，使用 http 模块',
          'execute → 生成代码：http.createServer((req,res) => res.end("Hello World"))',
          'verify → 验证：检查端口号和返回内容',
        ],
        output: '生成 server.js，node server.js 即可访问 http://localhost:3000',
        tips: ['使用 --criteria "监听 3000 端口" 指定端口', '使用 --criteria "返回 Hello World" 指定内容'],
      },
      {
        title: '进阶：实现 RESTful 博客 API',
        complexity: '进阶',
        scenario: '开发博客后端 API，支持文章 CRUD、评论、标签、分页、搜索、JWT 鉴权',
        command: '/loop-langgraph "开发博客 RESTful API" --criteria "文章 CRUD" --criteria "评论功能" --criteria "JWT 鉴权"',
        flow: [
          'analyze → 分析 API 需求，识别实体：文章、评论、用户',
          'plan → 拆分任务：User 模块 → Article 模块 → Comment 模块 → 搜索模块',
          'execute[1] → 生成 User 模块：注册、登录、JWT 中间件',
          'verify[1] → 验证 JWT 鉴权是否正确',
          'execute[2] → 生成 Article 模块：CRUD、分页、搜索',
          'verify[2] → 验证分页和搜索逻辑',
          'execute[3] → 生成 Comment 模块：评论 CRUD、嵌套评论',
          'verify[3] → 验证评论关联',
        ],
        output: '完整的博客 API 项目，包含 routes/、models/、middleware/ 目录',
        tips: ['每个 --criteria 对应一个子模块', '模块之间可能有依赖关系'],
      },
      {
        title: '高级：构建实时聊天应用',
        complexity: '高级',
        scenario: '基于 WebSocket 的多人实时聊天室，支持群聊、私聊、消息持久化、在线状态',
        command: '/loop-langgraph "构建实时聊天应用" --criteria "支持群聊" --criteria "支持私聊" --criteria "消息保存到 MongoDB"',
        flow: [
          'analyze → 分析：WebSocket 服务、房间管理、消息路由、持久化层',
          'plan → 分层：连接层 → 消息路由层 → 存储层 → 前端 UI',
          'execute → 实现 ws 服务器 + 房间管理 + MongoDB 存储',
          'verify → 多客户端连接测试、消息广播测试',
        ],
        output: 'server.js（WebSocket 服务）+ client.html（前端聊天界面）',
        tips: ['--criteria "消息不丢失" 确保可靠性', '--criteria "支持 100 人同时在线" 定义容量'],
      },
      {
        title: '专家：实现分布式任务调度器',
        complexity: '专家',
        scenario: '实现生产级分布式任务调度系统，支持任务分发、Worker 管理、失败重试、优先级队列、Cron 定时任务',
        command: '/loop-langgraph "实现分布式任务调度系统" --criteria "Worker 动态注册" --criteria "失败自动重试 3 次" --criteria "支持优先级队列"',
        flow: [
          'analyze → 分析调度系统核心组件',
          'plan → 设计：Scheduler + Worker + Queue + Monitor 四组件',
          'execute → 实现 Redis 队列 + Worker 注册 + 心跳检测 + 重试策略',
          'verify → 压力测试：1000 任务并发调度',
        ],
        output: '生产级调度系统，包含 scheduler.js、worker.js、queue.js、monitor.js',
        tips: ['先用 --criteria "单 Worker 正常" 验证基础', '再逐步添加多 Worker、优先级、Cron 等高级功能'],
      },
    ],
    bestPractices: [
      '先定义清晰的成功标准（--criteria），再执行主任务',
      '将复杂目标拆分为多个可验证的子目标',
      '使用条件跳转来处理重试和异常流程',
      '每个节点的输出应该是可验证的',
      '设置合理的 --max-iterations 防止无限循环',
      '状态对象应尽量精简，只保留必要信息',
    ],
    commonPitfalls: [
      '❌ 目标太模糊：❌ "做个网站" → ✅ "做个博客网站，支持文章 CRUD、评论、标签"',
      '❌ 没有成功标准：❌ 不设置 --criteria → ✅ 设置 3-5 个具体的 --criteria',
      '❌ 节点太多：❌ 一个节点做太多事 → ✅ 每个节点只做一件事',
      '❌ 忘记循环退出条件：❌ 永远重试 → ✅ 设置 --max-iterations 上限',
      '❌ 状态对象过大：❌ 把所有数据放状态里 → ✅ 只放当前步骤需要的数据',
    ],
    comparison: [
      { strategy: 'langgraph', whenToUse: '需要精确控制流程、条件分支、循环重试', whenNotToUse: '目标模糊需要 AI 自主探索' },
      { strategy: 'crew', whenToUse: '需要多角色协作、团队任务', whenNotToUse: '单人单任务、流程固定' },
      { strategy: 'autogpt', whenToUse: '需要复杂任务分解、并发执行', whenNotToUse: '需要精确控制执行顺序' },
      { strategy: 'openhands', whenToUse: '需要计划-执行-验证的迭代循环', whenNotToUse: '一次性执行、无需验证' },
      { strategy: 'swe-agent', whenToUse: 'Bug 修复、代码调试', whenNotToUse: '功能开发、新模块创建' },
    ],
    performance: [
      '简单任务（1-5 轮）：通常 10-30 秒完成',
      '中等任务（5-15 轮）：通常 1-5 分钟完成',
      '复杂任务（15-20 轮）：通常 5-15 分钟完成',
      '每轮迭代消耗 API tokens 约 2000-5000',
      '建议 --task-budget 设置为 50000-100000 tokens',
    ],
    customization: [
      '可以通过 --max-iterations 控制最大循环次数',
      '可以通过 --task-budget 控制 API 调用成本',
      '可以组合多个 --criteria 来定义复杂成功标准',
      '可以和其他策略组合使用（先用 langgraph 探索，再用 crew 执行）',
    ],
  },

  crew: {
    name: 'crew',
    displayName: 'CrewAI 多 Agent 协作引擎',
    tagline: '模拟真实团队协作，多角色分工合作完成复杂任务',
    overview: `CrewAI 策略模拟真实软件开发团队的协作流程，将任务分配给不同角色的 Agent（经理、开发者、测试、审查员），每个角色各司其职、迭代协作，共同完成复杂目标。

与 LangGraph 的"精确控制流程"不同，CrewAI 强调"角色分工"和"团队协作"。每个角色有独立的目标、工具、知识领域，通过任务委托和信息共享来协作。

核心能力：
- 角色定义：Manager（分配任务）、Developer（写代码）、Tester（写测试）、Reviewer（审查）
- 任务编排：Manager 分解任务并分配给合适的角色
- 迭代返工：Reviewer 不通过时自动返回到 Developer 修改
- 知识共享：角色间可以传递上下文和中间结果
- 并行执行：无依赖的任务可以并行执行`,
    useCases: [
      '需要多角色协作的复杂项目',
      '需要代码审查和质量控制的场景',
      '需要测试驱动开发（TDD）的项目',
      '需要多模块并行开发的场景',
      '需要迭代改进和返工的任务',
      '模拟真实团队协作的教学场景',
    ],
    notSuitableFor: [
      '单步骤的简单任务',
      '需要精确控制执行顺序的场景',
      '对执行时间敏感的快速任务',
      '不需要团队协作的个人任务',
    ],
    coreConcepts: [
      { term: 'Agent（角色）', definition: '具有特定角色、目标、工具和知识的智能体' },
      { term: 'Task（任务）', definition: '分配给角色的具体工作单元' },
      { term: 'Crew（团队）', definition: '由多个 Agent 组成的协作团队' },
      { term: 'Manager（经理）', definition: '负责任务分解、分配和协调的角色' },
      { term: 'Developer（开发者）', definition: '负责编写代码实现的角色' },
      { term: 'Tester（测试）', definition: '负责编写测试用例的角色' },
      { term: 'Reviewer（审查员）', definition: '负责代码审查和质量把关的角色' },
      { term: 'Rework（返工）', definition: '审查不通过时，任务返回到开发者修改' },
    ],
    architecture: [
      '+-----------------------------------------------------------+',
      '|                    CrewAI 架构图                           |',
      '+-----------------------------------------------------------+',
      '|                                                           |',
      '|  +----------------------------------------------------+  |',
      '|  |                  Manager（经理）                     |  |',
      '|  |  - 接收目标 -> 分解为子任务 -> 分配给角色           |  |',
      '|  |  - 监控进度 -> 协调角色间协作 -> 验收最终结果       |  |',
      '|  +-----------+-------------+-------------+-----------+  |',
      '|              |             |             |              |',
      '|              V             V             V              |',
      '|  +--------------+  +--------------+  +--------------+  |',
      '|  |  Developer   |  |   Tester     |  |   Reviewer   |  |',
      '|  |   (开发者)   |  |   (测试)     |  |   (审查员)   |  |',
      '|  |              |  |              |  |              |  |',
      '|  | - 编写代码   |  | - 编写测试   |  | - 代码审查   |  |',
      '|  | - 实现功能   |  | - 验证功能   |  | - 质量评估   |  |',
      '|  | - 修复 bug   |  | - 发现 bug   |  | - 提出建议   |  |',
      '|  +------+-------+  +------+-------+  +------+-------+  |',
      '|         |                 |                 |            |',
      '|         +-----------------+-----------------+            |',
      '|                           |                              |',
      '|                           V                              |',
      '|              +--------------------------+               |',
      '|              |   返工循环（Rework）      |               |',
      '|              |                          |               |',
      '|   Reviewer 不通过 -> Developer 修改 -> Tester 重测       |',
      '|                           |                              |',
      '|                           V                              |',
      '|                  Reviewer 通过 -> 完成                   |',
      '+-----------------------------------------------------------+',
    ].join('\n'),
    executionFlow: [
      '1. Manager 接收目标，分析需求，分解为子任务',
      '2. Manager 将子任务分配给 Developer（开发）和 Tester（测试）',
      '3. Developer 编写代码实现功能',
      '4. Tester 编写测试用例验证功能',
      '5. Reviewer 审查代码质量和测试覆盖率',
      '6a. 审查通过 → 任务完成',
      '6b. 审查不通过 → 返回步骤 3（返工）',
      '7. Manager 汇总所有子任务结果，验收最终交付物',
    ],
    parameters: [
      { name: '--strategy', type: 'string', default: 'crew', description: '固定为 crew，指定使用多 Agent 协作引擎' },
      { name: '--criteria', type: 'string[]', default: '[]', description: '成功标准列表，每个标准会被分配给对应角色验证' },
      { name: '--max-iterations', type: 'number', default: '20', description: '最大迭代次数（含返工）' },
      { name: '--max-retries', type: 'number', default: '2', description: '单个任务的最大返工次数' },
    ],
    examples: [
      {
        title: '入门：代码审查并修复 bug',
        complexity: '入门',
        scenario: '审查 src/utils.js 中的潜在 bug 并修复',
        command: '/loop-crew "审查 src/utils.js 中的潜在 bug 并修复"',
        flow: [
          'Manager → 分配审查任务给 Reviewer',
          'Reviewer → 发现 3 个潜在 bug（空指针、类型错误、边界条件）',
          'Developer → 修复 3 个 bug',
          'Tester → 编写复现测试确认修复',
          'Reviewer → 确认修复通过',
        ],
        output: '修复后的 utils.js + 测试用例 + 审查报告',
        tips: ['指定文件路径可以让审查更精确', '使用 --criteria "零 console.warn" 定义质量标准'],
      },
      {
        title: '进阶：博客系统全栈开发',
        complexity: '进阶',
        scenario: '开发个人博客系统，包含前端 UI、后端 API、数据库、管理后台',
        command: '/loop-crew "开发个人博客系统" --criteria "文章展示" --criteria "评论功能" --criteria "管理后台"',
        flow: [
          'Manager → 拆分为：数据库设计、后端 API、前端 UI、管理后台',
          'Developer[1] → 设计数据库 Schema（User、Article、Comment）',
          'Developer[2] → 开发后端 API（Express + MongoDB）',
          'Developer[3] → 开发前端 UI（React + Tailwind）',
          'Tester → 编写集成测试验证前后端联调',
          'Reviewer → 审查代码质量和安全漏洞',
        ],
        output: '完整的博客系统项目，包含前后端代码和测试',
        tips: ['每个 --criteria 对应一个子模块', '模块间有依赖时 Manager 会自动排序'],
      },
      {
        title: '高级：电商核心模块开发',
        complexity: '高级',
        scenario: '开发电商平台核心：商品管理、购物车、订单处理、支付集成、库存管理',
        command: '/loop-crew "开发电商核心模块" --criteria "商品 CRUD" --criteria "购物车功能" --criteria "订单流程"',
        flow: [
          'Manager → 拆分为 5 个子任务，识别依赖关系',
          'Developer → 并行开发商品模块和购物车模块',
          'Developer → 开发订单模块（依赖商品模块）',
          'Developer → 开发支付模块（依赖订单模块）',
          'Tester → 端到端测试：浏览→加购→下单→支付→发货',
          'Reviewer → 安全审计：支付安全、库存一致性',
        ],
        output: '完整电商核心系统，支持从浏览到发货全流程',
        tips: ['支付模块需要 --criteria "支持支付宝" --criteria "支持微信支付"', '库存模块需要 --criteria "防止超卖"'],
      },
      {
        title: '专家：SaaS 多租户平台',
        complexity: '专家',
        scenario: '构建 SaaS 平台：多租户数据隔离、订阅计费、RBAC 权限、用量统计',
        command: '/loop-crew "构建 SaaS 多租户平台" --criteria "租户数据隔离" --criteria "订阅计费" --criteria "RBAC 权限"',
        flow: [
          'Manager → 分析 SaaS 核心能力，制定开发计划',
          'Developer → 实现租户中间件（数据隔离）',
          'Developer → 实现订阅引擎（计费、升级、降级）',
          'Developer → 实现权限系统（角色、权限、策略）',
          'Tester → 多租户隔离测试、计费准确性测试',
          'Reviewer → 安全审计：租户数据泄露风险',
        ],
        output: '生产级 SaaS 基础平台，可快速开发垂直应用',
        tips: ['租户隔离是核心 --criteria "租户 A 看不到租户 B 的数据"', '计费需要 --criteria "支持按月/按年/按量计费"'],
      },
    ],
    bestPractices: [
      '为每个子任务设置明确的 --criteria，方便对应角色验证',
      '利用返工机制持续改进，不要期望一次通过',
      'Manager 会自动识别任务依赖关系，按正确顺序执行',
      '复杂项目建议拆分为 3-5 个子任务，每个子任务 1 个 --criteria',
      '返工次数不宜过多，建议 --max-retries 设为 2-3',
    ],
    commonPitfalls: [
      '❌ 角色冲突：❌ 给 Developer 和 Reviewer 相同目标 → ✅ 明确分工',
      '❌ 任务过大：❌ "开发整个系统" → ✅ 拆分为 3-5 个子任务',
      '❌ 没有质量标准：❌ 不设置 --criteria → ✅ 每个子任务 1-2 个标准',
      '❌ 返工次数过多：❌ --max-retries 10 → ✅ 2-3 次即可',
      '❌ 忽略依赖关系：❌ 并行开发有依赖的模块 → ✅ 让 Manager 自动排序',
    ],
    comparison: [
      { strategy: 'crew', whenToUse: '多角色协作、需要审查和质量控制', whenNotToUse: '单步骤任务、个人开发' },
      { strategy: 'langgraph', whenToUse: '精确控制流程、条件分支', whenNotToUse: '需要团队协作' },
      { strategy: 'autogpt', whenToUse: '复杂任务分解、并发执行', whenNotToUse: '需要角色分工' },
      { strategy: 'openhands', whenToUse: '计划-执行-验证循环', whenNotToUse: '需要多人协作' },
      { strategy: 'swe-agent', whenToUse: 'Bug 修复、代码调试', whenNotToUse: '功能开发' },
    ],
    performance: [
      '简单任务（2-3 个角色）：通常 1-3 分钟',
      '中等任务（3-4 个角色）：通常 3-8 分钟',
      '复杂任务（4-5 个角色 + 返工）：通常 8-15 分钟',
      '每个角色每轮消耗 API tokens 约 3000-8000',
      '建议 --task-budget 设置为 100000-200000 tokens',
    ],
    customization: [
      '可以通过 --max-retries 控制返工次数',
      '可以通过 --criteria 定义每个子任务的质量标准',
      '可以组合使用：先用 crew 开发，再用 swe-agent 修 bug',
    ],
  },

  autogpt: {
    name: 'autogpt',
    displayName: 'AutoGPT 图执行引擎',
    tagline: '将复杂任务分解为可执行的图结构，支持并发和智能重试',
    overview: `AutoGPT 策略将任务分解为有向无环图（DAG），每个节点是一个可执行的任务单元，边表示任务间的依赖关系。引擎自动分析依赖，按拓扑顺序执行，支持并发执行无依赖的任务。

与 LangGraph 的"条件跳转"不同，AutoGPT 专注于"任务分解"和"并行执行"。它会自动识别哪些任务可以并行，哪些必须串行，最大化执行效率。

核心能力：
- 任务分解：将复杂目标拆分为原子级子任务
- 依赖分析：自动识别任务间的依赖关系
- 并行执行：无依赖的任务同时执行，提升效率
- 智能重试：失败任务自动重试，支持指数退避
- 结果合并：子任务结果自动合并为最终输出`,
    useCases: [
      '可以分解为多个独立子任务的复杂目标',
      '需要并行执行提升效率的场景',
      '任务间有明确依赖关系的场景',
      '需要智能重试和容错处理的场景',
      '数据处理管道、ETL 流程',
      '自动化测试套件、CI/CD 流水线',
    ],
    notSuitableFor: [
      '需要条件分支和循环的场景',
      '需要多角色协作的场景',
      '单步骤的简单任务',
      '需要人工审批的流程',
    ],
    coreConcepts: [
      { term: 'Block（任务块）', definition: '原子级任务单元，包含输入、处理逻辑、输出' },
      { term: 'Graph（图）', definition: '由 Block 和边组成的有向无环图' },
      { term: 'Dependency（依赖）', definition: '任务间的先后关系，A 依赖 B 则 B 先执行' },
      { term: 'Parallel Execution（并行执行）', definition: '无依赖的任务同时执行' },
      { term: 'Retry Policy（重试策略）', definition: '失败时的重试规则，支持指数退避' },
      { term: 'Result Aggregation（结果聚合）', definition: '子任务结果合并为最终输出' },
    ],
    architecture: [
      '+-----------------------------------------------------------+',
      '|                    AutoGPT 架构图                          |',
      '+-----------------------------------------------------------+',
      '|                                                           |',
      '|  +---------+     +---------+     +---------+             |',
      '|  |  START  |---->| 分解任务 |---->| 分析依赖 |             |',
      '|  +---------+     +---------+     +----+----+             |',
      '|                                        |                  |',
      '|                    +-------------------+-------------+   |',
      '|                    |                   |             |   |',
      '|                    V                   V             V   |',
      '|              +---------+        +---------+   +---------+ |',
      '|              | 任务 A  |        | 任务 B  |   | 任务 C  | |',
      '|              |(无依赖) |        |(无依赖) |   |(依赖A,B)| |',
      '|              +----+----+        +----+----+   +----+----+ |',
      '|                   |                  |            |      |',
      '|                   |   并行执行       |            |      |',
      '|                   +--------+---------+            |      |',
      '|                            |                      |      |',
      '|                            V                      V      |',
      '|                      +---------+            +---------+  |',
      '|                      | 任务 D  |            | 任务 E  |  |',
      '|                      |(依赖A,B) |            |(依赖C)  |  |',
      '|                      +----+----+            +----+----+  |',
      '|                           |                      |       |',
      '|                           +----------+-----------+       |',
      '|                                      |                   |',
      '|                                      V                   |',
      '|                              +-------------+            |',
      '|                              |  结果聚合   |            |',
      '|                              +------+------+            |',
      '|                                     |                   |',
      '|                                     V                   |',
      '|                              +-------------+            |',
      '|                              |    END      |            |',
      '|                              +-------------+            |',
      '+-----------------------------------------------------------+',
    ].join('\n'),
    executionFlow: [
      '1. 任务分解：将复杂目标拆分为原子级子任务',
      '2. 依赖分析：识别任务间的依赖关系，构建 DAG',
      '3. 拓扑排序：确定执行顺序，无依赖的任务优先',
      '4. 并行执行：同时执行所有无依赖的任务',
      '5. 智能重试：失败任务按指数退避策略重试',
      '6. 结果聚合：所有子任务完成后合并结果',
      '7. 输出交付：生成最终交付物',
    ],
    parameters: [
      { name: '--strategy', type: 'string', default: 'autogpt', description: '固定为 autogpt，指定使用图执行引擎' },
      { name: '--criteria', type: 'string[]', default: '[]', description: '成功标准列表，每个子任务完成后验证' },
      { name: '--max-iterations', type: 'number', default: '20', description: '最大迭代次数' },
      { name: '--max-concurrency', type: 'number', default: '3', description: '最大并发任务数' },
      { name: '--retry-delay', type: 'number', default: '1000', description: '重试延迟基数（毫秒），指数退避' },
    ],
    examples: [
      {
        title: '入门：批量重命名项目文件',
        complexity: '入门',
        scenario: '将 src/ 下所有 .js 文件重命名为 kebab-case',
        command: '/loop-autogpt "将 src/ 下所有 .js 文件重命名为 kebab-case，空格替换为连字符"',
        flow: [
          '分解 → 扫描文件 → 生成映射 → 批量重命名',
          '执行 → fs.readdirSync + rename',
          '验证 → 检查所有文件是否符合 kebab-case',
        ],
        output: 'src/ 下所有文件变为 kebab-case 命名',
        tips: ['使用 --criteria "支持预览模式" 先看效果再执行'],
      },
      {
        title: '进阶：日志分析与异常检测',
        complexity: '进阶',
        scenario: '分析 access.log，统计请求数、错误率、异常 IP，生成 HTML 报告',
        command: '/loop-autogpt "分析 access.log，统计每小时请求数、错误率 Top 10、异常 IP、生成 HTML 报告"',
        flow: [
          '分解 → 解析日志 → 聚合统计 → 异常检测 → 生成报告',
          '并行 → 解析和统计可同时进行',
          '聚合 → 合并统计结果生成 HTML',
        ],
        output: 'report.html，包含趋势图、错误率饼图、异常 IP 列表',
        tips: ['--criteria "支持按小时聚合" 定义时间粒度', '--criteria "识别异常 IP" 定义检测目标'],
      },
      {
        title: '高级：CI/CD 流水线搭建',
        complexity: '高级',
        scenario: '配置 GitHub Actions 流水线：代码检查→测试→构建→部署→通知',
        command: '/loop-autogpt "配置 GitHub Actions 流水线" --criteria "ESLint 检查" --criteria "Jest 测试" --criteria "Docker 构建"',
        flow: [
          '分解 → 分析项目技术栈 → 设计流水线阶段 → 生成 YAML',
          '并行 → ESLint 和 Jest 可并行执行',
          '串行 → Docker 构建依赖测试通过 → K8s 部署依赖构建成功',
        ],
        output: '.github/workflows/deploy.yml，提交代码后自动部署',
        tips: ['每个 --criteria 对应流水线的一个阶段', '--criteria "支持自动回滚" 增加容错'],
      },
      {
        title: '专家：全栈项目脚手架',
        complexity: '专家',
        scenario: '开发 create-doge-app 脚手架，支持选择 React/Vue + Node/Go + MySQL/MongoDB',
        command: '/loop-autogpt "开发 create-doge-app 脚手架" --criteria "支持 React" --criteria "支持 Vue" --criteria "支持 Node"',
        flow: [
          '分解 → 设计交互 CLI → 模板引擎 → 依赖安装 → 示例代码',
          '并行 → React 和 Vue 模板可并行生成',
          '合并 → 整合为完整脚手架工具',
        ],
        output: 'npx create-doge-app my-app 一键生成可运行的全栈项目',
        tips: ['--criteria "支持 TypeScript" 增加语言选项', '--criteria "包含部署配置" 增加实用性'],
      },
    ],
    bestPractices: [
      '将复杂目标拆分为 3-7 个子任务，每个子任务独立可验证',
      '利用并行执行提升效率，无依赖的任务会自动并行',
      '设置合理的 --max-concurrency 控制并发数',
      '使用指数退避重试策略处理临时性失败',
      '每个子任务设置 --criteria 确保质量',
    ],
    commonPitfalls: [
      '❌ 任务粒度过粗：❌ "开发整个系统" → ✅ 拆分为 5-10 个子任务',
      '❌ 忽略依赖关系：❌ 并行执行有依赖的任务 → ✅ 让引擎自动分析依赖',
      '❌ 并发过高：❌ --max-concurrency 10 → ✅ 3-5 即可',
      '❌ 没有重试策略：❌ 失败就放弃 → ✅ 设置指数退避重试',
      '❌ 结果未聚合：❌ 子任务各自为政 → ✅ 定义清晰的输出格式',
    ],
    comparison: [
      { strategy: 'autogpt', whenToUse: '任务分解、并行执行、智能重试', whenNotToUse: '需要条件分支和循环' },
      { strategy: 'langgraph', whenToUse: '精确控制流程、条件跳转', whenNotToUse: '需要并行执行' },
      { strategy: 'crew', whenToUse: '多角色协作、团队任务', whenNotToUse: '自动化批处理' },
      { strategy: 'openhands', whenToUse: '计划-执行-验证循环', whenNotToUse: '一次性批处理' },
      { strategy: 'swe-agent', whenToUse: 'Bug 修复', whenNotToUse: '功能开发' },
    ],
    performance: [
      '简单任务（1-3 个子任务）：通常 30 秒 - 2 分钟',
      '中等任务（3-7 个子任务）：通常 2-5 分钟',
      '复杂任务（7-15 个子任务）：通常 5-10 分钟',
      '并行执行可提升 2-3 倍效率',
      '建议 --max-concurrency 设为 3-5',
    ],
    customization: [
      '可以通过 --max-concurrency 控制并发数',
      '可以通过 --retry-delay 控制重试延迟',
      '可以通过 --criteria 定义每个子任务的验证标准',
    ],
  },

  openhands: {
    name: 'openhands',
    displayName: 'OpenHands 工程代理循环',
    tagline: '计划-执行-验证三阶段循环，迭代改进直到目标达成',
    overview: `OpenHands 策略采用经典的"计划-执行-验证"三阶段循环，每个迭代周期包含：
1. Planner：分析当前状态，制定下一步计划
2. Executor：按计划执行具体操作
3. Verifier：验证执行结果，决定是否继续

这种模式特别适合需要反复迭代、持续改进的工程任务。与 LangGraph 的"预定义流程"不同，OpenHands 的每个阶段都由 AI 动态决策，更灵活但确定性较低。

核心能力：
- 动态计划：根据当前状态实时调整计划
- 迭代改进：失败时自动调整策略重新尝试
- 结果验证：每个阶段都有明确的验证标准`,
    useCases: [
      '需要反复迭代改进的任务',
      '目标明确但路径不清晰的场景',
      '需要验证每一步执行结果的场景',
      '代码重构、性能优化、安全加固',
      '需要持续反馈和调整的任务',
    ],
    notSuitableFor: [
      '流程固定、不需要迭代的场景',
      '需要多角色协作的任务',
      '一次性执行的批处理任务',
      '需要并行执行的场景',
    ],
    coreConcepts: [
      { term: 'Planner（计划器）', definition: '分析当前状态和目标差距，制定下一步执行计划' },
      { term: 'Executor（执行器）', definition: '按计划执行具体操作，产出中间结果' },
      { term: 'Verifier（验证器）', definition: '验证执行结果是否满足成功标准' },
      { term: 'Iteration（迭代）', definition: '一次完整的计划-执行-验证循环' },
      { term: 'Feedback Loop（反馈循环）', definition: '验证失败时反馈给 Planner 调整计划' },
    ],
    architecture: [
      '+-----------------------------------------------------------+',
      '|                  OpenHands 架构图                          |',
      '+-----------------------------------------------------------+',
      '|                                                           |',
      '|              +--------------------------+                  |',
      '|              |     目标 + 约束          |                  |',
      '|              +------------+-------------+                  |',
      '|                           |                                |',
      '|                           V                                |',
      '|              +--------------------------+                  |',
      '|              |       Planner            |                  |',
      '|              |       (计划器)           |                  |',
      '|              |                          |                  |',
      '|              |  - 分析现状              |                  |',
      '|              |  - 识别差距              |                  |',
      '|              |  - 制定计划              |                  |',
      '|              +------------+-------------+                  |',
      '|                           |                                |',
      '|                           V                                |',
      '|              +--------------------------+                  |',
      '|              |       Executor           |                  |',
      '|              |       (执行器)           |                  |',
      '|              |                          |                  |',
      '|              |  - 执行计划              |                  |',
      '|              |  - 产出结果              |                  |',
      '|              |  - 记录日志              |                  |',
      '|              +------------+-------------+                  |',
      '|                           |                                |',
      '|                           V                                |',
      '|              +--------------------------+                  |',
      '|              |       Verifier           |                  |',
      '|              |       (验证器)           |                  |',
      '|              |                          |                  |',
      '|              |  - 检查标准              |                  |',
      '|              |  - 评估结果              |                  |',
      '|              |  - 决定下一步            |                  |',
      '|              +------------+-------------+                  |',
      '|                           |                                |',
      '|                 +---------+---------+                      |',
      '|                 |                   |                      |',
      '|                 V                   V                      |',
      '|           +----------+       +----------+                 |',
      '|           |  通过    |       |  失败    |                 |',
      '|           |  → 完成  |       |  → 返回  |                 |',
      '|           +----------+       |  Planner |                 |',
      '|                              +----------+                 |',
      '+-----------------------------------------------------------+',
    ].join('\n'),
    executionFlow: [
      '1. Planner 分析目标和当前状态，识别差距',
      '2. Planner 制定下一步执行计划',
      '3. Executor 按计划执行具体操作',
      '4. Verifier 验证执行结果是否满足成功标准',
      '5a. 验证通过 → 检查是否达到最终目标 → 是则完成',
      '5b. 验证通过 → 检查是否达到最终目标 → 否则返回步骤 1',
      '5c. 验证失败 → 分析失败原因 → 调整计划 → 返回步骤 2',
    ],
    parameters: [
      { name: '--strategy', type: 'string', default: 'openhands', description: '固定为 openhands，指定使用工程代理循环' },
      { name: '--criteria', type: 'string[]', default: '[]', description: '成功标准列表，Verifier 据此验证结果' },
      { name: '--max-iterations', type: 'number', default: '20', description: '最大迭代次数' },
    ],
    examples: [
      {
        title: '入门：修复拼写错误和格式问题',
        complexity: '入门',
        scenario: '扫描并修复 src/ 下所有文件的拼写错误和格式问题',
        command: '/loop-openhands "扫描并修复 src/ 下所有文件的拼写错误和格式问题"',
        flow: [
          'Planner → 使用 cspell + ESLint 扫描问题',
          'Executor → 自动修复可修复的问题',
          'Verifier → 确认无新问题引入',
        ],
        output: '代码库拼写错误清零，格式统一',
        tips: ['使用 --criteria "ESLint 零警告" 定义质量标准'],
      },
      {
        title: '进阶：优化数据库查询性能',
        complexity: '进阶',
        scenario: '分析慢查询日志，添加索引，优化 JOIN，减少全表扫描',
        command: '/loop-openhands "分析并优化慢查询" --criteria "查询时间 < 100ms" --criteria "不使用 SELECT *"',
        flow: [
          'Planner → EXPLAIN 分析执行计划，识别全表扫描',
          'Executor → 添加合适索引，重写低效 SQL',
          'Verifier → 对比优化前后耗时',
        ],
        output: '数据库查询性能提升 10 倍',
        tips: ['--criteria "查询时间 < 100ms" 定义性能目标', '--criteria "添加索引不超过 5 个" 控制成本'],
      },
      {
        title: '高级：架构迁移（单体→微服务）',
        complexity: '高级',
        scenario: '制定渐进式迁移计划，拆分服务边界，设计数据同步方案',
        command: '/loop-openhands "制定从单体到微服务的渐进迁移计划" --criteria "支持灰度发布" --criteria "支持回滚"',
        flow: [
          'Planner → 领域分析，识别服务边界',
          'Executor → 绞杀者模式逐步迁移',
          'Verifier → 双跑对比，确认数据一致性',
        ],
        output: '平滑完成架构迁移，用户零感知',
        tips: ['--criteria "服务独立部署" 定义拆分目标', '--criteria "数据零丢失" 定义安全目标'],
      },
      {
        title: '专家：安全审计与漏洞修复',
        complexity: '专家',
        scenario: '全面安全审计：SQL 注入、XSS、CSRF、敏感数据泄露，逐一修复',
        command: '/loop-openhands "全面安全审计并修复" --criteria "OWASP Top 10 零漏洞" --criteria "通过渗透测试"',
        flow: [
          'Planner → OWASP Top 10 检查清单',
          'Executor → 逐一修复漏洞（参数化查询、HTML 转义、CSP）',
          'Verifier → 渗透测试确认修复',
        ],
        output: '安全等级从 C 提升到 A',
        tips: ['--criteria "通过 OWASP ZAP 扫描" 定义验证标准', '--criteria "通过手工渗透测试" 增加可靠性'],
      },
    ],
    bestPractices: [
      '设置明确的 --criteria 作为 Verifier 的验证标准',
      '每次迭代只做一件事，便于定位问题',
      '失败时分析根本原因，而不是简单重试',
      '记录每次迭代的变更，便于回滚',
      '设置合理的 --max-iterations 防止无限循环',
    ],
    commonPitfalls: [
      '❌ 没有验证标准：❌ 不设置 --criteria → ✅ 设置 3-5 个具体标准',
      '❌ 计划过大：❌ 一次改太多 → ✅ 每次迭代只做一件事',
      '❌ 忽略失败原因：❌ 简单重试 → ✅ 分析原因调整策略',
      '❌ 无限循环：❌ 不设 --max-iterations → ✅ 设置 10-20 次上限',
      '❌ 没有回滚机制：❌ 改坏了无法恢复 → ✅ 每次迭代前备份',
    ],
    comparison: [
      { strategy: 'openhands', whenToUse: '迭代改进、计划-执行-验证', whenNotToUse: '流程固定、无需迭代' },
      { strategy: 'langgraph', whenToUse: '精确控制流程', whenNotToUse: '需要动态调整计划' },
      { strategy: 'crew', whenToUse: '多角色协作', whenNotToUse: '单人迭代' },
      { strategy: 'autogpt', whenToUse: '并行执行', whenNotToUse: '串行迭代' },
      { strategy: 'swe-agent', whenToUse: 'Bug 修复', whenNotToUse: '功能开发' },
    ],
    performance: [
      '简单任务（1-3 次迭代）：通常 30 秒 - 2 分钟',
      '中等任务（3-8 次迭代）：通常 2-5 分钟',
      '复杂任务（8-20 次迭代）：通常 5-15 分钟',
      '每次迭代消耗 API tokens 约 3000-6000',
      '建议 --max-iterations 设为 10-20',
    ],
    customization: [
      '可以通过 --criteria 定义 Verifier 的验证标准',
      '可以通过 --max-iterations 控制最大迭代次数',
      '可以组合使用：先用 openhands 优化，再用 swe-agent 修残留 bug',
    ],
  },

  'swe-agent': {
    name: 'swe-agent',
    displayName: 'SWE-agent Bug 修复引擎',
    tagline: '定位→分析→生成补丁→验证，自动迭代直到 bug 修复',
    overview: `SWE-agent 是专门针对软件调试和 Bug 修复的策略，它采用"定位→分析→生成补丁→验证"的四阶段循环，自动迭代直到 bug 被修复或重试次数用尽。

与其他策略不同，SWE-agent 专注于"问题解决"而非"功能开发"。它擅长分析错误日志、定位根因、生成最小化修复补丁。

核心能力：
- 错误定位：从堆栈追踪快速定位问题代码
- 根因分析：分析 bug 产生的根本原因
- 补丁生成：生成最小化、安全的修复补丁
- 自动验证：运行测试确认修复有效
- 轨迹记录：完整记录调试过程，便于复盘`,
    useCases: [
      '修复运行时异常（NullPointerException、TypeError 等）',
      '修复内存泄漏和资源耗尽问题',
      '修复并发问题（死锁、竞态条件）',
      '修复安全漏洞（SQL 注入、XSS）',
      '修复性能退化和响应缓慢',
      '修复数据不一致和损坏问题',
    ],
    notSuitableFor: [
      '功能开发和模块创建',
      '代码重构和架构迁移',
      '文档编写和测试用例设计',
      '需要多角色协作的复杂项目',
    ],
    coreConcepts: [
      { term: 'Localize（定位）', definition: '从错误日志和堆栈追踪中找到问题代码位置' },
      { term: 'Analyze（分析）', definition: '分析 bug 产生的根本原因' },
      { term: 'Patch（补丁）', definition: '生成最小化、安全的修复代码' },
      { term: 'Verify（验证）', definition: '运行测试确认修复有效且不引入新问题' },
      { term: 'Trajectory（轨迹）', definition: '完整的调试过程记录' },
      { term: 'Cost Tracking（成本追踪）', definition: '记录 API 调用成本和进度' },
    ],
    architecture: [
      '+-----------------------------------------------------------+',
      '|                  SWE-agent 架构图                          |',
      '+-----------------------------------------------------------+',
      '|                                                           |',
      '|  +---------------------------------------------------+   |',
      '|  |              错误报告 / 堆栈日志                    |   |',
      '|  +------------------------+--------------------------+   |',
      '|                           |                              |',
      '|                           V                              |',
      '|              +--------------------------+                |',
      '|              |       Localize           |                |',
      '|              |       (定位)             |                |',
      '|              |                          |                |',
      '|              |  - 解析堆栈              |                |',
      '|              |  - 定位文件              |                |',
      '|              |  - 定位行号              |                |',
      '|              +------------+-------------+                |',
      '|                           |                              |',
      '|                           V                              |',
      '|              +--------------------------+                |',
      '|              |       Analyze            |                |',
      '|              |       (分析)             |                |',
      '|              |                          |                |',
      '|              |  - 根因分析              |                |',
      '|              |  - 影响范围              |                |',
      '|              |  - 修复策略              |                |',
      '|              +------------+-------------+                |',
      '|                           |                              |',
      '|                           V                              |',
      '|              +--------------------------+                |',
      '|              |       Patch              |                |',
      '|              |       (补丁)             |                |',
      '|              |                          |                |',
      '|              |  - 生成修复              |                |',
      '|              |  - 最小化变更            |                |',
      '|              |  - 安全验证              |                |',
      '|              +------------+-------------+                |',
      '|                           |                              |',
      '|                           V                              |',
      '|              +--------------------------+                |',
      '|              |       Verify             |                |',
      '|              |       (验证)             |                |',
      '|              |                          |                |',
      '|              |  - 运行测试              |                |',
      '|              |  - 回归检查              |                |',
      '|              |  - 确认修复              |                |',
      '|              +------------+-------------+                |',
      '|                           |                              |',
      '|                 +---------+---------+                    |',
      '|                 |                   |                    |',
      '|                 V                   V                    |',
      '|           +----------+       +----------+               |',
      '|           |  通过    |       |  失败    |               |',
      '|           |  → 完成  |       |  → 返回  |               |',
      '|           +----------+       |  Analyze |               |',
      '|                              +----------+               |',
      '+-----------------------------------------------------------+',
    ].join('\n'),
    executionFlow: [
      '1. Localize：解析错误日志和堆栈追踪，定位问题文件和行号',
      '2. Analyze：分析问题代码，确定根本原因',
      '3. Patch：生成最小化修复补丁',
      '4. Verify：运行测试确认修复有效',
      '5a. 测试通过 → 检查是否有回归 → 无回归则完成',
      '5b. 测试通过 → 检查是否有回归 → 有回归则返回步骤 2',
      '5c. 测试失败 → 分析失败原因 → 返回步骤 2',
    ],
    parameters: [
      { name: '--strategy', type: 'string', default: 'swe-agent', description: '固定为 swe-agent，指定使用 Bug 修复引擎' },
      { name: '--criteria', type: 'string[]', default: '[]', description: '成功标准列表，验证修复是否满足要求' },
      { name: '--max-iterations', type: 'number', default: '20', description: '最大迭代次数' },
      { name: '--max-budget', type: 'number', default: '10', description: '最大 API 调用预算（美元）' },
    ],
    examples: [
      {
        title: '入门：修复 NullPointerException',
        complexity: '入门',
        scenario: '修复 src/auth.js 第 42 行的空指针异常',
        command: '/loop-swe-agent "修复 src/auth.js 第 42 行的 NullPointerException"',
        flow: [
          'Localize → 堆栈追踪指向 auth.js:42',
          'Analyze → user 对象可能为 null',
          'Patch → 添加 user?.name 安全访问',
          'Verify → 运行测试确认修复',
        ],
        output: 'NullPointerException 修复，添加防御性编程',
        tips: ['使用 --criteria "添加单元测试覆盖该场景" 防止回归'],
      },
      {
        title: '进阶：修复内存泄漏',
        complexity: '进阶',
        scenario: '修复 server.js 中的内存泄漏：服务运行 24 小时后 OOM',
        command: '/loop-swe-agent "修复 server.js 中的内存泄漏：服务运行 24 小时后 OOM" --criteria "7x24 小时稳定运行"',
        flow: [
          'Localize → heapdump 对比分析',
          'Analyze → 事件监听器未移除 + 大对象缓存未释放',
          'Patch → 添加 removeListener + LRU 缓存',
          'Verify → 压力测试确认内存稳定',
        ],
        output: '内存泄漏修复，服务可长期稳定运行',
        tips: ['--criteria "内存波动 < 20%" 定义稳定性目标', '--criteria "支持 1000 并发" 定义容量目标'],
      },
      {
        title: '高级：修复 SQL 注入漏洞',
        complexity: '高级',
        scenario: '修复 userDao.js 中的 SQL 注入：search 参数直接拼接到 SQL',
        command: '/loop-swe-agent "修复 userDao.js 中的 SQL 注入漏洞" --criteria "通过 SQL 注入测试" --criteria "所有查询参数化"',
        flow: [
          'Localize → 找到字符串拼接 SQL 的代码',
          'Analyze → 用户输入未转义直接拼接',
          'Patch → 改为参数化查询 + 输入白名单验证',
          'Verify → SQL 注入测试确认修复',
        ],
        output: 'SQL 注入漏洞修复，通过 OWASP ZAP 安全扫描',
        tips: ['--criteria "通过 OWASP ZAP 扫描" 定义安全标准', '--criteria "所有查询参数化" 定义修复目标'],
      },
      {
        title: '专家：修复分布式一致性问题',
        complexity: '专家',
        scenario: '修复 order-service 分布式事务：订单已支付但库存未扣减',
        command: '/loop-swe-agent "修复 order-service 分布式事务：订单已支付但库存未扣减" --criteria "数据最终一致" --criteria "支持幂等重试"',
        flow: [
          'Localize → 分布式链路追踪定位问题',
          'Analyze → 支付和库存操作非原子',
          'Patch → 引入 Saga 模式 + 幂等校验',
          'Verify → 模拟故障注入测试',
        ],
        output: '分布式事务修复，支付和库存数据 100% 一致',
        tips: ['--criteria "支持幂等重试" 定义容错目标', '--criteria "数据最终一致" 定义一致性目标'],
      },
    ],
    bestPractices: [
      '提供完整的错误日志和堆栈追踪，便于定位',
      '设置明确的 --criteria 作为修复验证标准',
      '每次只修复一个 bug，避免混淆',
      '修复后运行完整测试套件，防止回归',
      '记录修复过程，便于后续复盘',
    ],
    commonPitfalls: [
      '❌ 没有错误日志：❌ "有 bug" → ✅ 提供完整堆栈追踪',
      '❌ 修复范围过大：❌ 一次改太多文件 → ✅ 最小化修复',
      '❌ 没有回归测试：❌ 改完不测试 → ✅ 运行完整测试套件',
      '❌ 忽略根因：❌ 只治标不治本 → ✅ 分析根本原因',
      '❌ 没有验证标准：❌ 不设置 --criteria → ✅ 设置具体的验证标准',
    ],
    comparison: [
      { strategy: 'swe-agent', whenToUse: 'Bug 修复、代码调试', whenNotToUse: '功能开发、新模块创建' },
      { strategy: 'langgraph', whenToUse: '精确控制流程', whenNotToUse: '需要 AI 自主调试' },
      { strategy: 'crew', whenToUse: '多角色协作', whenNotToUse: '单人调试' },
      { strategy: 'autogpt', whenToUse: '并行执行', whenNotToUse: '串行调试' },
      { strategy: 'openhands', whenToUse: '迭代改进', whenNotToUse: '一次性修复' },
    ],
    performance: [
      '简单 bug（1-3 次迭代）：通常 30 秒 - 2 分钟',
      '中等 bug（3-8 次迭代）：通常 2-5 分钟',
      '复杂 bug（8-20 次迭代）：通常 5-15 分钟',
      '每次迭代消耗 API tokens 约 2000-5000',
      '建议 --max-budget 设为 5-10 美元',
    ],
    customization: [
      '可以通过 --criteria 定义修复验证标准',
      '可以通过 --max-budget 控制 API 调用成本',
      '可以通过 --max-iterations 控制最大尝试次数',
      '可以组合使用：先用 swe-agent 修 bug，再用 openhands 优化',
    ],
  },
}
